import { useCallback, useEffect, useMemo, useState, type FormEvent, type ReactNode } from 'react'
import { Navigate, NavLink, Route, Routes, useLocation, useNavigate } from 'react-router-dom'
import { AlertTriangle, Barcode, Boxes, Building2, ClipboardCheck, Factory, LayoutDashboard, LogOut, Menu, Package, ReceiptText, RefreshCw, ScanLine, ShieldAlert, ShoppingCart, Truck, Users, Warehouse as WarehouseIcon, X } from 'lucide-react'
import { authApi, barcodeApi, dashboardApi, inventoryApi, materialsApi, productionApi, productsApi, purchaseOrderApi, qualityApi, reorderApi, suppliersApi, transferApi, userApi, warehouseApi } from './api'
import type { ApiError, AuthResponse, Batch, DashboardSummary, Role } from './types'

type Toast = { type: 'success' | 'error'; message: string } | null
type Field = { key: string; label: string; type?: 'text' | 'email' | 'number' | 'date' | 'password' | 'select'; required?: boolean; options?: string[]; help?: string }
type ResourceItem = { id: string }
type ResourceApi<T> = { list: () => Promise<T[]>; create?: (body: Record<string, unknown>) => Promise<T>; update?: (id: string, body: Record<string, unknown>) => Promise<T> }

const roleLabel = (role: Role) => role.replaceAll('_', ' ').toLowerCase().replace(/\b\w/g, (c) => c.toUpperCase())
const apiMessage = (error: unknown) => (error as ApiError).message ?? 'Something went wrong.'
const statusClass = (status: unknown) => String(status).includes('AVAILABLE') || String(status).includes('COMPLETED') || String(status).includes('RECEIVED') || String(status).includes('PASSED') ? 'bg-emerald-100 text-emerald-800' : String(status).includes('REJECTED') || String(status).includes('FAILED') ? 'bg-rose-100 text-rose-800' : 'bg-amber-100 text-amber-800'
const date = (value: unknown) => value ? new Date(String(value)).toLocaleString() : '—'
const can = (role: Role, allowed: Role[]) => allowed.includes(role)

function Login({ onLogin }: { onLogin: (session: AuthResponse) => void }) {
  const [mode, setMode] = useState<'login' | 'register'>('login'); const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [unitId, setUnitId] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  const submit = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setError(''); try { const session = mode === 'login' ? await authApi.login({ email, password }) : await authApi.register({ name, email, password, unitId: unitId || undefined }); onLogin(session) } catch (e) { setError(apiMessage(e)) } finally { setBusy(false) } }
  const switchMode = () => { setMode(mode === 'login' ? 'register' : 'login'); setError('') }
  const isRegister = mode === 'register'
  return <main className="min-h-screen bg-slate-950 px-4 py-12"><div className="mx-auto grid max-w-5xl overflow-hidden rounded-2xl bg-white shadow-2xl md:grid-cols-2"><section className="bg-teal-800 p-10 text-white"><Package size={40} /><h1 className="mt-12 text-4xl font-bold">StockAI</h1><p className="mt-3 text-teal-100">Inventory and operations for Sri Vidha Polymers.</p><div className="mt-16 border-t border-teal-600 pt-5 text-sm text-teal-100">{isRegister ? 'Create the first Super Admin account to begin.' : 'Sign in to manage inventory and operations.'}</div></section><section className="p-8 md:p-12"><h2 className="text-2xl font-bold">{isRegister ? 'Create first account' : 'Welcome back'}</h2><p className="mt-2 text-sm text-slate-500">{isRegister ? 'This is available only until the first Super Admin is created.' : 'Enter your StockAI account details.'}</p><form onSubmit={submit} className="mt-8 grid gap-5">{isRegister && <><label className="field">Full name<input required minLength={2} className="input" value={name} onChange={(e) => setName(e.target.value)} autoComplete="name" /></label><label className="field">Unit ID <span className="font-normal text-slate-400">(optional)</span><input className="input" value={unitId} onChange={(e) => setUnitId(e.target.value)} /></label></>}<label className="field">Email<input required type="email" className="input" value={email} onChange={(e) => setEmail(e.target.value)} autoComplete="email" /></label><label className="field">Password<input required minLength={isRegister ? 12 : undefined} type="password" className="input" value={password} onChange={(e) => setPassword(e.target.value)} autoComplete={isRegister ? 'new-password' : 'current-password'} />{isRegister && <span className="text-xs font-normal text-slate-500">At least 12 characters, as required by the backend.</span>}</label>{error && <Notice type="error">{error}</Notice>}<button className="btn-primary mt-2" disabled={busy}>{busy ? 'Please wait…' : isRegister ? 'Create Super Admin account' : 'Sign in'}</button></form><button type="button" className="mt-5 text-sm font-medium text-teal-700 hover:text-teal-800" onClick={switchMode}>{isRegister ? 'Already have an account? Sign in' : 'No account yet? Create the first Super Admin account'}</button></section></div></main>
}
function Notice({ type, children }: { type: 'success' | 'error'; children: ReactNode }) { return <div className={`rounded-lg border px-3 py-2 text-sm ${type === 'error' ? 'border-rose-200 bg-rose-50 text-rose-800' : 'border-emerald-200 bg-emerald-50 text-emerald-800'}`}>{children}</div> }
function Empty({ children }: { children: ReactNode }) { return <div className="card p-10 text-center text-sm text-slate-500">{children}</div> }

type NavItem = { group: string; to: string; label: string; icon: typeof LayoutDashboard; roles: Role[] }
const nav: NavItem[] = [
  { group: 'Main', to: '/', label: 'Dashboard', icon: LayoutDashboard, roles: [] as Role[] },
  { group: 'Inventory', to: '/materials', label: 'Materials', icon: Boxes, roles: ['SUPER_ADMIN', 'STORE_MANAGER', 'PURCHASE_MANAGER', 'WAREHOUSE_EXECUTIVE'] },
  { group: 'Inventory', to: '/inventory', label: 'Inventory', icon: Package, roles: ['SUPER_ADMIN', 'STORE_MANAGER', 'PRODUCTION_MANAGER', 'QUALITY_MANAGER', 'WAREHOUSE_EXECUTIVE', 'DISPATCH_EXECUTIVE'] },
  { group: 'Inventory', to: '/products', label: 'Finished Products', icon: Factory, roles: ['SUPER_ADMIN', 'STORE_MANAGER', 'PRODUCTION_MANAGER'] },
  { group: 'Inventory', to: '/scan', label: 'Scan QR', icon: ScanLine, roles: ['SUPER_ADMIN', 'STORE_MANAGER', 'WAREHOUSE_EXECUTIVE'] },
  { group: 'Operations', to: '/production', label: 'Production', icon: Factory, roles: ['SUPER_ADMIN', 'PRODUCTION_MANAGER'] },
  { group: 'Operations', to: '/warehouses', label: 'Warehouses', icon: WarehouseIcon, roles: ['SUPER_ADMIN', 'PLANT_MANAGER', 'STORE_MANAGER'] },
  { group: 'Operations', to: '/transfers', label: 'Stock Transfers', icon: Truck, roles: ['SUPER_ADMIN', 'PLANT_MANAGER', 'STORE_MANAGER', 'WAREHOUSE_EXECUTIVE'] },
  { group: 'Purchasing', to: '/suppliers', label: 'Suppliers', icon: Building2, roles: ['SUPER_ADMIN', 'PURCHASE_MANAGER'] },
  { group: 'Purchasing', to: '/purchase-orders', label: 'Purchase Orders', icon: ShoppingCart, roles: ['SUPER_ADMIN', 'PURCHASE_MANAGER'] },
  { group: 'Purchasing', to: '/reorder', label: 'Reorder Suggestions', icon: AlertTriangle, roles: ['SUPER_ADMIN', 'PURCHASE_MANAGER', 'STORE_MANAGER'] },
  { group: 'Quality', to: '/quality', label: 'Quality Inspections', icon: ClipboardCheck, roles: ['SUPER_ADMIN', 'QUALITY_MANAGER'] },
  { group: 'Insights', to: '/alerts', label: 'Alerts', icon: ShieldAlert, roles: ['SUPER_ADMIN', 'PLANT_MANAGER', 'STORE_MANAGER', 'PURCHASE_MANAGER'] },
  { group: 'Insights', to: '/reports', label: 'Reports', icon: ReceiptText, roles: ['SUPER_ADMIN', 'FACTORY_DIRECTOR', 'PLANT_MANAGER'] },
  { group: 'Admin', to: '/users', label: 'Users', icon: Users, roles: ['SUPER_ADMIN'] },
]
function Shell({ session, onLogout, children }: { session: AuthResponse; onLogout: () => void; children: ReactNode }) {
 const [open, setOpen] = useState(false); const location = useLocation(); const title = nav.find((item) => item.to === location.pathname)?.label ?? 'StockAI'; const allowed = nav.filter((item) => !item.roles.length || can(session.user.role, item.roles))
 const side = <aside className="flex h-full w-72 flex-col bg-slate-950 text-slate-100"><div className="flex items-center gap-3 px-6 py-6 text-xl font-bold"><Package className="text-teal-300" />StockAI</div><nav className="flex-1 overflow-auto px-3">{Array.from(new Set(allowed.map((x) => x.group))).map((group) => <div className="mb-5" key={group}><p className="px-3 pb-2 text-xs font-bold uppercase tracking-wider text-slate-500">{group}</p>{allowed.filter((x) => x.group === group).map((item) => { const Icon = item.icon; return <NavLink end={item.to === '/'} to={item.to} key={item.to} onClick={() => setOpen(false)} className={({ isActive }) => `mb-1 flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm ${isActive ? 'bg-teal-700 text-white' : 'text-slate-300 hover:bg-slate-800'}`}><Icon size={18} />{item.label}</NavLink> })}</div>)}</nav><button onClick={onLogout} className="m-3 flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm text-slate-300 hover:bg-slate-800"><LogOut size={18} />Sign out</button></aside>
 return <div className="min-h-screen md:flex"><div className="hidden md:block">{side}</div>{open && <div className="fixed inset-0 z-50 md:hidden"><button aria-label="Close navigation" className="absolute inset-0 bg-slate-950/50" onClick={() => setOpen(false)} /><div className="relative h-full">{side}</div></div>}<section className="min-w-0 flex-1"><header className="flex items-center justify-between border-b border-slate-200 bg-white px-4 py-3 md:px-8"><div className="flex items-center gap-3"><button className="btn-secondary p-2 md:hidden" onClick={() => setOpen(true)}><Menu size={20} /></button><div><h1 className="font-bold text-slate-900">{title}</h1><p className="hidden text-xs text-slate-500 sm:block">Sri Vidha Polymers</p></div></div><div className="text-right"><p className="text-sm font-semibold">{session.user.name}</p><p className="text-xs text-teal-700">{roleLabel(session.user.role)}</p></div></header><main className="mx-auto max-w-7xl p-4 md:p-8">{children}</main></section></div>
}

function useData<T>(load: () => Promise<T>) { const [data, setData] = useState<T | null>(null); const [error, setError] = useState(''); const [loading, setLoading] = useState(true); const refresh = useCallback(async () => { setLoading(true); setError(''); try { setData(await load()) } catch (e) { setError(apiMessage(e)) } finally { setLoading(false) } }, [load]); useEffect(() => { const id = window.setTimeout(() => { void refresh() }, 0); return () => window.clearTimeout(id) }, [refresh]); return { data, error, loading, refresh } }
function Dashboard() { const { data, error, loading, refresh } = useData<DashboardSummary>(dashboardApi.summary); if (loading) return <Empty>Loading dashboard…</Empty>; if (error) return <ErrorState message={error} retry={refresh} />; if (!data) return null; return <div className="grid gap-5"><div className="grid gap-4 sm:grid-cols-3"><Metric label="Available stock" value={data.availableStock.quantity.toLocaleString()} detail="Total quantity" /><Metric label="Available batches" value={String(data.availableStock.batches)} detail="Ready for operations" /><Metric label="In quarantine" value={String(data.quarantineBatches)} detail="Awaiting inspection" /></div><section className="card overflow-hidden"><div className="flex items-center justify-between border-b border-slate-200 p-5"><div><h2 className="font-bold">Low stock materials</h2><p className="text-sm text-slate-500">Materials at or below their reorder point.</p></div><button className="btn-secondary" onClick={() => void refresh()}><RefreshCw size={16} />Refresh</button></div>{data.lowStock.length ? <Table rows={data.lowStock as unknown as ResourceItem[]} columns={['sku', 'name', 'category', 'reorderPoint', 'unit']} /> : <div className="p-8 text-center text-sm text-slate-500">No low-stock materials right now.</div>}</section></div> }
function Metric({ label, value, detail }: { label: string; value: string; detail: string }) { return <div className="card p-5"><p className="label">{label}</p><p className="mt-2 text-3xl font-bold text-slate-900">{value}</p><p className="mt-1 text-sm text-slate-500">{detail}</p></div> }
function ErrorState({ message, retry }: { message: string; retry: () => Promise<void> }) { return <Empty><p className="mb-3 text-rose-700">{message}</p><button className="btn-secondary" onClick={() => void retry()}><RefreshCw size={16} />Try again</button></Empty> }
function Table({ rows, columns, actions }: { rows: ResourceItem[]; columns: string[]; actions?: (row: ResourceItem) => ReactNode }) { const [query, setQuery] = useState(''); const values = (row: ResourceItem) => row as unknown as Record<string, unknown>; const filtered = rows.filter((row) => Object.values(values(row)).some((value) => String(value ?? '').toLowerCase().includes(query.toLowerCase()))); return <div className="overflow-x-auto"><div className="p-4"><input aria-label="Search records" className="input max-w-sm" placeholder="Search records…" value={query} onChange={(e) => setQuery(e.target.value)} /></div><table className="table"><thead><tr>{columns.map((x) => <th key={x}>{x.replace(/([A-Z])/g, ' $1')}</th>)}{actions && <th>Actions</th>}</tr></thead><tbody>{filtered.map((row) => { const source = values(row); return <tr key={row.id}>{columns.map((column) => <td key={column}>{column === 'status' ? <span className={`status ${statusClass(source[column])}`}>{String(source[column])}</span> : column.endsWith('At') ? date(source[column]) : Array.isArray(source[column]) ? String(source[column].length) : String(source[column] ?? '—')}</td>)}{actions && <td><div className="flex flex-wrap gap-2">{actions(row)}</div></td>}</tr> })}</tbody></table>{!filtered.length && <div className="p-8 text-center text-sm text-slate-500">No records match your search.</div>}</div> }

function ResourcePage<T extends ResourceItem>({ title, description, api, fields, columns, role, edit = true }: { title: string; description: string; api: ResourceApi<T>; fields: Field[]; columns: string[]; role: Role; edit?: boolean }) { const { data, error, loading, refresh } = useData(api.list); const [show, setShow] = useState(false); const [editing, setEditing] = useState<T | null>(null); const [toast, setToast] = useState<Toast>(null); const permitted = api.create && can(role, actionRoles(title)); const save = async (body: Record<string, unknown>) => { try { if (editing && api.update) await api.update(editing.id, body); else if (api.create) await api.create(body); setToast({ type: 'success', message: editing ? 'Record updated.' : 'Record created.' }); setShow(false); setEditing(null); await refresh() } catch (e) { setToast({ type: 'error', message: apiMessage(e) }) } }
 if (loading) return <Empty>Loading {title.toLowerCase()}…</Empty>; if (error) return <ErrorState message={error} retry={refresh} />; return <div className="grid gap-5"><PageIntro title={title} description={description} action={permitted ? <button className="btn-primary" onClick={() => { setEditing(null); setShow(true) }}>Add {title.slice(0, -1)}</button> : undefined} />{toast && <Notice type={toast.type}>{toast.message}</Notice>}{data?.length ? <section className="card overflow-hidden"><Table rows={data} columns={columns} actions={edit && api.update && permitted ? (row) => <button className="btn-secondary" onClick={() => { setEditing(row as T); setShow(true) }}>Edit</button> : undefined} /></section> : <Empty>No {title.toLowerCase()} found.{permitted ? ' Create the first one to get started.' : ''}</Empty>}{show && <RecordForm title={`${editing ? 'Edit' : 'Add'} ${title.slice(0, -1)}`} fields={fields} initial={editing ?? undefined} onClose={() => { setShow(false); setEditing(null) }} onSave={save} />}</div> }
function actionRoles(title: string): Role[] { const map: Record<string, Role[]> = { Materials: ['SUPER_ADMIN', 'STORE_MANAGER', 'PURCHASE_MANAGER'], Products: ['SUPER_ADMIN', 'STORE_MANAGER', 'PRODUCTION_MANAGER'], Suppliers: ['SUPER_ADMIN', 'PURCHASE_MANAGER'], Warehouses: ['SUPER_ADMIN', 'PLANT_MANAGER', 'STORE_MANAGER'], Users: ['SUPER_ADMIN'] }; return map[title] ?? [] }
function PageIntro({ title, description, action }: { title: string; description: string; action?: ReactNode }) { return <div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-2xl font-bold text-slate-900">{title}</h2><p className="mt-1 text-sm text-slate-500">{description}</p></div>{action}</div> }
function RecordForm({ title, fields, initial, onClose, onSave }: { title: string; fields: Field[]; initial?: ResourceItem; onClose: () => void; onSave: (body: Record<string, unknown>) => Promise<void> }) { const initialValues = useMemo(() => { const source = initial as unknown as Record<string, unknown> | undefined; return Object.fromEntries(fields.map((f) => [f.key, source?.[f.key] ?? ''])) }, [fields, initial]); const [values, setValues] = useState<Record<string, unknown>>(initialValues); const [busy, setBusy] = useState(false); const submit = async (event: FormEvent) => { event.preventDefault(); setBusy(true); const body = Object.fromEntries(fields.map((f) => [f.key, f.type === 'number' && values[f.key] !== '' ? Number(values[f.key]) : values[f.key] || null])); await onSave(body); setBusy(false) }; return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/50 p-4"><form onSubmit={submit} className="max-h-[90vh] w-full max-w-xl overflow-auto rounded-xl bg-white p-6 shadow-xl"><div className="mb-5 flex items-center justify-between"><h3 className="text-lg font-bold">{title}</h3><button type="button" className="btn-secondary p-2" onClick={onClose}><X size={18} /></button></div><div className="grid gap-4 sm:grid-cols-2">{fields.map((f) => <label className="field" key={f.key}>{f.label}<input required={f.required} type={f.type ?? 'text'} className="input" value={String(values[f.key] ?? '')} onChange={(e) => setValues({ ...values, [f.key]: e.target.value })} />{f.help && <span className="text-xs font-normal text-slate-500">{f.help}</span>}</label>)}</div><div className="mt-6 flex justify-end gap-3"><button type="button" className="btn-secondary" onClick={onClose}>Cancel</button><button className="btn-primary" disabled={busy}>{busy ? 'Saving…' : 'Save'}</button></div></form></div> }

const materialFields: Field[] = [{ key: 'sku', label: 'SKU', required: true }, { key: 'name', label: 'Name', required: true }, { key: 'category', label: 'Category', required: true }, { key: 'unit', label: 'Unit', required: true }, { key: 'reorderPoint', label: 'Reorder point', type: 'number' }, { key: 'leadTimeDays', label: 'Lead time (days)', type: 'number' }]
const productFields: Field[] = materialFields.filter((f) => f.key !== 'leadTimeDays')
const supplierFields: Field[] = [{ key: 'name', label: 'Name', required: true }, { key: 'contactName', label: 'Contact name' }, { key: 'email', label: 'Email', type: 'email' }, { key: 'phone', label: 'Phone' }, { key: 'gstin', label: 'GSTIN' }, { key: 'leadTimeDays', label: 'Lead time (days)', type: 'number' }]
const warehouseFields: Field[] = [{ key: 'name', label: 'Name', required: true }, { key: 'unitId', label: 'Unit ID', required: true }, { key: 'type', label: 'Type', required: true }, { key: 'address', label: 'Address' }, { key: 'capacity', label: 'Capacity', type: 'number' }, { key: 'capacityUnit', label: 'Capacity unit' }]
const userFields: Field[] = [{ key: 'name', label: 'Name', required: true }, { key: 'email', label: 'Email', type: 'email', required: true }, { key: 'password', label: 'Password (12+ chars)', type: 'password', required: true }, { key: 'role', label: 'Role', required: true, help: 'Use a backend role value, e.g. STORE_MANAGER.' }, { key: 'unitId', label: 'Unit ID' }, { key: 'warehouseIds', label: 'Warehouse IDs', help: 'Comma-separated IDs.' }]

function InventoryPage({ role }: { role: Role }) { const { data, error, loading, refresh } = useData<Batch[]>(inventoryApi.list); const [toast, setToast] = useState<Toast>(null); const [form, setForm] = useState<'batch' | 'movement' | null>(null); const actions = can(role, ['SUPER_ADMIN', 'STORE_MANAGER', 'WAREHOUSE_EXECUTIVE']); const release = async (id: string) => { try { await inventoryApi.release(id); setToast({ type: 'success', message: 'Batch released to available stock.' }); await refresh() } catch (e) { setToast({ type: 'error', message: apiMessage(e) }) } }; if (loading) return <Empty>Loading inventory…</Empty>; if (error) return <ErrorState message={error} retry={refresh} />; return <div className="grid gap-5"><PageIntro title="Inventory" description="Batch-level stock records from the backend." action={<div className="flex gap-2">{actions && <><button className="btn-secondary" onClick={() => setForm('movement')}>Record movement</button><button className="btn-primary" onClick={() => setForm('batch')}>Receive batch</button></>}</div>} />{toast && <Notice type={toast.type}>{toast.message}</Notice>}{data?.length ? <section className="card overflow-hidden"><Table rows={data} columns={['batchNumber', 'materialId', 'warehouseId', 'quantity', 'uom', 'status', 'barcode']} actions={(row) => <>{(row as unknown as { status?: string }).status === 'QUARANTINE' && can(role, ['SUPER_ADMIN', 'QUALITY_MANAGER']) && <button className="btn-secondary" onClick={() => void release(row.id)}>Release</button>}</>} /></section> : <Empty>No batches found.</Empty>}{form === 'batch' && <RecordForm title="Receive batch" fields={[{ key: 'batchNumber', label: 'Batch number', required: true }, { key: 'materialId', label: 'Material ID', required: true }, { key: 'supplierLot', label: 'Supplier lot' }, { key: 'warehouseId', label: 'Warehouse ID', required: true }, { key: 'unitId', label: 'Unit ID', required: true }, { key: 'quantity', label: 'Quantity', type: 'number', required: true }, { key: 'uom', label: 'UOM', required: true }, { key: 'expiresAt', label: 'Expiry date', type: 'date' }, { key: 'barcode', label: 'Barcode' }]} onClose={() => setForm(null)} onSave={async (body) => { await inventoryApi.create(body); setToast({ type: 'success', message: 'Batch received in quarantine.' }); setForm(null); await refresh() }} />}{form === 'movement' && <RecordForm title="Record movement" fields={[{ key: 'batchId', label: 'Batch ID', required: true }, { key: 'type', label: 'Type', required: true, help: 'Allowed: CONSUMPTION, SCRAP, ADJUSTMENT, DISPATCH.' }, { key: 'quantity', label: 'Quantity', type: 'number', required: true }, { key: 'toWarehouseId', label: 'Destination warehouse ID' }, { key: 'reference', label: 'Reference' }]} onClose={() => setForm(null)} onSave={async (body) => { await inventoryApi.move(body); setToast({ type: 'success', message: 'Movement recorded.' }); setForm(null); await refresh() }} />}</div> }
function ProductionPage({ role }: { role: Role }) { const { data, error, loading, refresh } = useData(productionApi.list); const [form, setForm] = useState<'start' | string | null>(null); const [toast, setToast] = useState<Toast>(null); const allowed = can(role, ['SUPER_ADMIN', 'PRODUCTION_MANAGER']); if (loading) return <Empty>Loading production runs…</Empty>; if (error) return <ErrorState message={error} retry={refresh} />; const start = async (body: Record<string, unknown>) => { const consumptions = String(body.consumptions).split(',').filter(Boolean).map((item) => { const [batchId, quantity] = item.trim().split(':'); return { batchId, quantity: Number(quantity) } }); await productionApi.create({ productId: body.productId, unitId: body.unitId, warehouseId: body.warehouseId, consumptions }); setForm(null); setToast({ type: 'success', message: 'Production run started.' }); await refresh() }; return <div className="grid gap-5"><PageIntro title="Production" description="Start and complete production runs." action={allowed ? <button className="btn-primary" onClick={() => setForm('start')}>Start run</button> : undefined} />{toast && <Notice type={toast.type}>{toast.message}</Notice>}{data?.length ? <section className="card overflow-hidden"><Table rows={data as unknown as ResourceItem[]} columns={['runNumber', 'productId', 'warehouseId', 'status', 'outputQuantity', 'startedAt']} actions={(row) => (row as unknown as { status?: string }).status === 'IN_PROGRESS' && allowed ? <button className="btn-secondary" onClick={() => setForm(row.id)}>Complete</button> : undefined} /></section> : <Empty>No production runs found.</Empty>}{form === 'start' && <RecordForm title="Start production run" fields={[{ key: 'productId', label: 'Product ID', required: true }, { key: 'unitId', label: 'Unit ID', required: true }, { key: 'warehouseId', label: 'Warehouse ID', required: true }, { key: 'consumptions', label: 'Consumptions', required: true, help: 'Enter batchId:quantity pairs, separated by commas.' }]} onClose={() => setForm(null)} onSave={start} />}{form && form !== 'start' && <RecordForm title="Complete production run" fields={[{ key: 'outputQuantity', label: 'Output quantity', type: 'number', required: true }, { key: 'outputBatchNumber', label: 'Output batch number', required: true }, { key: 'outputUom', label: 'Output UOM', required: true }]} onClose={() => setForm(null)} onSave={async (body) => { await productionApi.complete(form, body); setForm(null); setToast({ type: 'success', message: 'Production run completed.' }); await refresh() }} />}</div> }
function TransfersPage({ role }: { role: Role }) { const { data, error, loading, refresh } = useData(transferApi.list); const [form, setForm] = useState(false); const [toast, setToast] = useState<Toast>(null); const createAllowed = can(role, ['SUPER_ADMIN', 'STORE_MANAGER', 'WAREHOUSE_EXECUTIVE']); const approval = can(role, ['SUPER_ADMIN', 'PLANT_MANAGER', 'STORE_MANAGER']); const receive = can(role, ['SUPER_ADMIN', 'STORE_MANAGER', 'WAREHOUSE_EXECUTIVE']); const action = async (id: string, method: 'approve' | 'receive') => { try { await transferApi[method](id); setToast({ type: 'success', message: `Transfer ${method}d.` }); await refresh() } catch (e) { setToast({ type: 'error', message: apiMessage(e) }) } }; if (loading) return <Empty>Loading transfers…</Empty>; if (error) return <ErrorState message={error} retry={refresh} />; return <div className="grid gap-5"><PageIntro title="Stock Transfers" description="Move available stock between warehouses." action={createAllowed ? <button className="btn-primary" onClick={() => setForm(true)}>Request transfer</button> : undefined} />{toast && <Notice type={toast.type}>{toast.message}</Notice>}{data?.length ? <section className="card overflow-hidden"><Table rows={data as unknown as ResourceItem[]} columns={['transferNumber', 'batchId', 'fromWarehouseId', 'toWarehouseId', 'quantity', 'status']} actions={(row) => { const status = (row as unknown as { status?: string }).status; return <>{status === 'PENDING' && approval && <button className="btn-secondary" onClick={() => void action(row.id, 'approve')}>Approve</button>}{status === 'APPROVED' && receive && <button className="btn-primary" onClick={() => void action(row.id, 'receive')}>Receive</button>}</> }} /></section> : <Empty>No stock transfers found.</Empty>}{form && <RecordForm title="Request transfer" fields={[{ key: 'batchId', label: 'Batch ID', required: true }, { key: 'fromWarehouseId', label: 'Source warehouse ID', required: true }, { key: 'toWarehouseId', label: 'Destination warehouse ID', required: true }, { key: 'quantity', label: 'Quantity', type: 'number', required: true }]} onClose={() => setForm(false)} onSave={async (body) => { await transferApi.create(body); setForm(false); setToast({ type: 'success', message: 'Transfer requested.' }); await refresh() }} />}</div> }
function QualityPage({ role }: { role: Role }) { const { data, error, loading, refresh } = useData(qualityApi.list); const [form, setForm] = useState(false); const [toast, setToast] = useState<Toast>(null); const allowed = can(role, ['SUPER_ADMIN', 'QUALITY_MANAGER']); if (loading) return <Empty>Loading inspections…</Empty>; if (error) return <ErrorState message={error} retry={refresh} />; return <div className="grid gap-5"><PageIntro title="Quality Inspections" description="Record quality results for batches." action={allowed ? <button className="btn-primary" onClick={() => setForm(true)}>New inspection</button> : undefined} />{toast && <Notice type={toast.type}>{toast.message}</Notice>}{data?.length ? <section className="card overflow-hidden"><Table rows={data as unknown as ResourceItem[]} columns={['batchId', 'stage', 'result', 'inspectedBy', 'createdAt']} /></section> : <Empty>No quality inspections found.</Empty>}{form && <RecordForm title="New quality inspection" fields={[{ key: 'batchId', label: 'Batch ID', required: true }, { key: 'stage', label: 'Stage', required: true }, { key: 'result', label: 'Result', required: true, help: 'PENDING, PASSED, or FAILED.' }, { key: 'notes', label: 'Notes' }, { key: 'tests', label: 'Tests', help: 'Optional entries: name:value:unit:withinSpec, separated by commas.' }]} onClose={() => setForm(false)} onSave={async (body) => { const tests = String(body.tests ?? '').split(',').filter(Boolean).map((item) => { const [name, value, unit, withinSpec] = item.trim().split(':'); return { name, value, unit, withinSpec: withinSpec === 'true' } }); await qualityApi.create({ batchId: body.batchId, stage: body.stage, result: body.result, notes: body.notes, tests }); setForm(false); setToast({ type: 'success', message: 'Inspection recorded.' }); await refresh() }} />}</div> }
function PurchaseOrdersPage({ role }: { role: Role }) { const { data, error, loading, refresh } = useData(purchaseOrderApi.list); const [form, setForm] = useState<'create' | string | null>(null); const [toast, setToast] = useState<Toast>(null); const allowed = can(role, ['SUPER_ADMIN', 'PURCHASE_MANAGER']); if (loading) return <Empty>Loading purchase orders…</Empty>; if (error) return <ErrorState message={error} retry={refresh} />; return <div className="grid gap-5"><PageIntro title="Purchase Orders" description="Create and update purchase order status." action={allowed ? <button className="btn-primary" onClick={() => setForm('create')}>Create purchase order</button> : undefined} />{toast && <Notice type={toast.type}>{toast.message}</Notice>}{data?.length ? <section className="card overflow-hidden"><Table rows={data as unknown as ResourceItem[]} columns={['poNumber', 'supplierId', 'status', 'createdBy']} actions={(row) => allowed ? <button className="btn-secondary" onClick={() => setForm(row.id)}>Update status</button> : undefined} /></section> : <Empty>No purchase orders found.</Empty>}{form === 'create' && <RecordForm title="Create purchase order" fields={[{ key: 'supplierId', label: 'Supplier ID', required: true }, { key: 'lines', label: 'Lines', required: true, help: 'Enter materialId:quantity:unitPrice pairs, separated by commas.' }]} onClose={() => setForm(null)} onSave={async (body) => { const lines = String(body.lines).split(',').filter(Boolean).map((line) => { const [materialId, quantity, unitPrice] = line.trim().split(':'); return { materialId, quantity: Number(quantity), unitPrice: Number(unitPrice) } }); await purchaseOrderApi.create({ supplierId: body.supplierId, lines }); setForm(null); setToast({ type: 'success', message: 'Purchase order created as draft.' }); await refresh() }} />}{form && form !== 'create' && <RecordForm title="Update purchase order status" fields={[{ key: 'status', label: 'Status', required: true, help: 'DRAFT, APPROVED, ORDERED, PART_RECEIVED, RECEIVED, or CANCELLED.' }]} onClose={() => setForm(null)} onSave={async (body) => { await purchaseOrderApi.status(form, String(body.status) as import('./types').PurchaseOrderStatus); setForm(null); setToast({ type: 'success', message: 'Purchase order updated.' }); await refresh() }} />}</div> }
function ScanPage({ role }: { role: Role }) { const [code, setCode] = useState(''); const [batch, setBatch] = useState<Batch | null>(null); const [label, setLabel] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const scan = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setError(''); setLabel(''); try { setBatch(await barcodeApi.scan(code.trim())) } catch (e) { setBatch(null); setError(apiMessage(e)) } finally { setBusy(false) } }; const createLabel = async () => { if (!batch) return; setError(''); try { const result = await barcodeApi.label(batch.id); setLabel(`QR code: ${result.code}`) } catch (e) { setError(apiMessage(e)) } }; return <div className="grid max-w-2xl gap-5"><PageIntro title="Scan QR" description="Look up a batch by its existing barcode." /><section className="card p-5"><form onSubmit={scan} className="flex flex-col gap-3 sm:flex-row"><input className="input" required placeholder="Enter barcode or code" value={code} onChange={(e) => setCode(e.target.value)} /><button className="btn-primary" disabled={busy}><Barcode size={17} />{busy ? 'Looking up…' : 'Look up'}</button></form></section>{error && <Notice type="error">{error}</Notice>}{batch && <section className="card p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="label">Batch</p><h3 className="text-xl font-bold">{batch.batchNumber}</h3></div><span className={`status ${statusClass(batch.status)}`}>{batch.status}</span></div><dl className="mt-5 grid gap-4 text-sm sm:grid-cols-2"><div><dt className="label">Quantity</dt><dd>{batch.quantity} {batch.uom}</dd></div><div><dt className="label">Warehouse ID</dt><dd>{batch.warehouseId}</dd></div><div><dt className="label">Material ID</dt><dd>{batch.materialId}</dd></div><div><dt className="label">Barcode</dt><dd>{batch.barcode ?? 'Not assigned'}</dd></div></dl>{can(role, ['SUPER_ADMIN', 'STORE_MANAGER', 'WAREHOUSE_EXECUTIVE']) && <button className="btn-secondary mt-5" onClick={() => void createLabel()}>Generate label</button>}{label && <Notice type="success">{label} Use your browser print command to print this label value.</Notice>}</section>}</div> }
function ReorderPage() { const { data, error, loading, refresh } = useData(reorderApi.list); if (loading) return <Empty>Loading reorder suggestions…</Empty>; if (error) return <ErrorState message={error} retry={refresh} />; return <div className="grid gap-5"><PageIntro title="Reorder Suggestions" description="Recommendations generated by the backend from available inventory." />{data?.length ? <section className="card overflow-hidden"><Table rows={data as unknown as ResourceItem[]} columns={['sku', 'name', 'availableQuantity', 'reorderPoint', 'suggestedQuantity', 'alert']} /></section> : <Empty>No reorder recommendations right now.</Empty>}</div> }
function ReportsPage() { return <div className="grid gap-5"><PageIntro title="Reports" description="Reporting capabilities." /><Empty>Backend does not currently provide an API for this feature.</Empty></div> }
function UsersPage({ role }: { role: Role }) { const api: ResourceApi<ResourceItem> = { list: async () => (await userApi.list()) as unknown as ResourceItem[], create: async (body) => userApi.create({ ...body, warehouseIds: String(body.warehouseIds ?? '').split(',').map((id) => id.trim()).filter(Boolean) }) as unknown as ResourceItem, update: async (id, body) => userApi.update(id, { name: body.name, role: body.role, unitId: body.unitId, warehouseIds: String(body.warehouseIds ?? '').split(',').map((x) => x.trim()).filter(Boolean) }) as unknown as ResourceItem }; return <ResourcePage title="Users" description="Manage backend user accounts and access roles." api={api} fields={userFields} columns={['name', 'email', 'role', 'unitId', 'active']} role={role} /> }

export function App() { const [session, setSession] = useState<AuthResponse | null>(() => { try { const raw = localStorage.getItem('stockai_session'); return raw ? JSON.parse(raw) as AuthResponse : null } catch { return null } }); const navigate = useNavigate(); const logout = useCallback(() => { localStorage.removeItem('stockai_session'); localStorage.removeItem('stockai_token'); setSession(null); navigate('/login') }, [navigate]); useEffect(() => { window.addEventListener('stockai:unauthorized', logout); return () => window.removeEventListener('stockai:unauthorized', logout) }, [logout]); const login = (next: AuthResponse) => { localStorage.setItem('stockai_session', JSON.stringify(next)); localStorage.setItem('stockai_token', next.accessToken); setSession(next); navigate('/') }; if (!session) return <Routes><Route path="/login" element={<Login onLogin={login} />} /><Route path="*" element={<Navigate to="/login" replace />} /></Routes>; const role = session.user.role; return <Shell session={session} onLogout={logout}><Routes><Route path="/" element={<Dashboard />} /><Route path="/materials" element={<ResourcePage title="Materials" description="Manage raw-material master records." api={materialsApi} fields={materialFields} columns={['sku', 'name', 'category', 'unit', 'reorderPoint', 'leadTimeDays']} role={role} />} /><Route path="/inventory" element={<InventoryPage role={role} />} /><Route path="/products" element={<ResourcePage title="Products" description="Manage finished-product records." api={productsApi} fields={productFields} columns={['sku', 'name', 'category', 'unit', 'reorderPoint']} role={role} />} /><Route path="/scan" element={<ScanPage role={role} />} /><Route path="/production" element={<ProductionPage role={role} />} /><Route path="/warehouses" element={<ResourcePage title="Warehouses" description="Manage warehouses and their operating status." api={warehouseApi} fields={warehouseFields} columns={['code', 'name', 'unitId', 'type', 'capacity', 'capacityUnit', 'active']} role={role} />} /><Route path="/transfers" element={<TransfersPage role={role} />} /><Route path="/suppliers" element={<ResourcePage title="Suppliers" description="Manage supplier master records." api={suppliersApi} fields={supplierFields} columns={['code', 'name', 'contactName', 'email', 'phone', 'leadTimeDays']} role={role} />} /><Route path="/purchase-orders" element={<PurchaseOrdersPage role={role} />} /><Route path="/reorder" element={<ReorderPage />} /><Route path="/alerts" element={<ReorderPage />} /><Route path="/quality" element={<QualityPage role={role} />} /><Route path="/reports" element={<ReportsPage />} /><Route path="/users" element={<UsersPage role={role} />} /><Route path="*" element={<Navigate to="/" replace />} /></Routes></Shell> }
