package com.vynedam.stockai.domain;
public enum Role { SUPER_ADMIN, FACTORY_DIRECTOR, PLANT_MANAGER, STORE_MANAGER, PURCHASE_MANAGER, PRODUCTION_MANAGER, QUALITY_MANAGER, WAREHOUSE_EXECUTIVE, DISPATCH_EXECUTIVE }
